config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :recipes
  devise_for :users
  root "home#index"
  resources :recipes

  scope "/admin" do
    resources :ingredients, except: %i[show]
    resources :ingredient_categories, except: %i[show]
    resources :recipe_categories, except: %i[show]
    resources :appliances, except: %i[show]
    resources :users, except: %i[show new create]
    resources :inventories
  end
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  belongs_to :recipe_category
  belongs_to :user

  validates :name, :description, :picture, presence: true

  has_one_attached :steps_video
  has_one_attached :picture do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end

  scope :with_ingredient, ->(ingredient) { where("recipes.ingredients->'needed' @> ?", [{ name: ingredient }].to_json) }
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :set_recipe_categories, except: %i[index]
  before_action :set_ingredients, except: %i[index]
  before_action :set_appliances, except: %i[index]
  before_action :set_ingredients_json, only: %i[show]

  # GET /recipes or /recipes.json
  def index
    if params[:is_searching].nil?
      @recipe_scope = params[:recipe_scope]
      @recipes = if @recipe_scope == "user"
                   current_user.recipes.order(updated_at: :desc)
                 else
                   Recipe.all.order(updated_at: :desc)
                 end
    else
      @recipes = filter_recipes(params[:search_by_ingredient].downcase)
    end
  end

  # GET /recipes/1
  def show; end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params.merge(user_id: current_user.id))

    if @recipe.save
      redirect_to recipe_url(@recipe), notice: "Recipe was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /recipes/1
  def update
    if @recipe.update(recipe_params.merge(user_id: current_user.id))
      redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy

    redirect_to recipes_url, notice: "Recipe was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = authorize Recipe.find(params[:id])
  end

  def set_recipe_categories
    @recipe_categories = RecipeCategory.all
  end

  def set_ingredients
    @ingredients = Ingredient.all
  end

  def set_appliances
    @appliances = Appliance.all
  end

  def set_ingredients_json
    @ingredients_json = @recipe.ingredients["needed"]
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    step_param = params[:recipe][:steps]
    appliance_param = params[:recipe][:appliances]
    ingredients_param = params[:recipe][:ingredients]

    filtered_params = params.require(:recipe).permit(:name, :description, :picture,
                                                     :ingredients, :appliances, :steps,
                                                     :recipe_category_id, :steps_video, :user_id)

    filtered_params.merge(steps: sanitize_steps(step_param),
                          appliances: sanitize_appliances(appliance_param),
                          ingredients: sanitize_ingredients(ingredients_param))
  end

  def sanitize_steps(param)
    param.split("\r\n").compact_blank if param.present?
  end

  def sanitize_appliances(param)
    param.split(",").compact_blank if param.present?
  end

  def sanitize_ingredients(param)
    JSON.parse(param)
  end

  def filter_recipes(ingredient)
    Recipe.with_ingredient(ingredient)
  end
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
  def categories_for_select(categories)
    categories.sort_by(&:name).map { |category| [category.name, category.id] }
  end

  def ingredients_for_select(ingredients)
    ingredients.sort_by(&:name).map { |ingredient| [ingredient.name.capitalize, ingredient.name] }
  end

  def appliances_for_select(appliances)
    appliances.sort_by(&:name).map { |appliance| [appliance.name.capitalize, appliance.name] }
  end

  def parsed_ingredients(recipe)
    JSON.parse(recipe.ingredients)["needed"]
  end
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, id: "recipesForm") do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :ingredients %>
  <%= form.hidden_field :appliances %>

  <div class="field">
    <%= form.label :name, class: "label" %>
    <div class="control">
      <%= form.text_field :name, autofocus: true, placeholder: "name", class: "input is-large is-primary" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :picture, class: "label" %>
    <div class="control">
      <div class="file is-primary">
        <label class="file-label">
          <%= form.file_field :picture, class: "file-input" %>
          <span class="file-cta">
            <span class="file-icon">
              <i class="fas fa-upload"></i>
            </span>
            <span class="file-label">
              Upload a picture of the results!
            </span>
          </span>
          <span class="file-name"></span>
        </label>
      </div>
    </div>
  </div>


  <div class="field">
    <%= form.label :recipe_category_id, class: "label" %>
    <div class="control">
      <div class="select is-primary">
        <%= form.select :recipe_category_id, categories_for_select(@recipe_categories), prompt: "Choose a category" %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :description, class: "label" %>
    <div class="control">
      <%= form.text_field :description, placeholder: "Describe your new recipe...", class: "input"  %>
    </div>
  </div>

  <hr class="login-hr">

  <h3 class="subtitle has-text-primary">Ingredients</h3>

  <div class="field has-addons has-addons-centered">
    <div class="control">
      <div class="select is-primary">
        <%= form.select "ingredient_select", ingredients_for_select(@ingredients) %>
      </div>      
    </div>
    <div class="control">
      <%= form.number_field "ingredient_amount", placeholder: "Amount", class: "input", min: 0.5, step: 0.5, pattern: "[0-9]" %>
    </div>
    <div class="control">
      <div class="select is-primary">
        <%= form.select "ingredient_measure", Ingredient::MEASURES %>
      </div>      
    </div>
    <div class="control">
      <%= form.button "Add", class: "button is-success", id: "ingredient_adder", type: "button" %>
    </div>
  </div>

  <h4 class="subtitle has-text-primary-dark">Required ingredients</h4>

  <div class="field is-grouped is-grouped-multiline" id="ingredient_pool"></div>

  <hr class="login-hr">

  <h3 class="subtitle has-text-primary">Appliances</h3>

  <div class="field has-addons has-addons-centered">
    <div class="control">
      <div class="select is-primary">
        <%= form.select "appliance_selector", appliances_for_select(@appliances) %>
      </div>      
    </div>
    <div class="control">
      <%= form.button "Add", class: "button is-success", id: "appliance_adder", type: "button" %>
    </div>
  </div>

  <h4 class="subtitle has-text-primary-dark">Required appliances</h4>

  <div class="field is-grouped is-grouped-multiline" id="appliance_pool"></div>

  <hr class="login-hr">

  <h3 class="subtitle has-text-primary">Steps</h3>

  <div class="field">
    <%= form.label :steps_video, class: "label" %>
    <div class="control">
      <div class="file is-primary">
        <label class="file-label">
          <%= form.file_field :steps_video, class: "file-input" %>
          <span class="file-cta">
            <span class="file-icon">
              <i class="fas fa-upload"></i>
            </span>
            <span class="file-label">
              Upload a video showing the procedure (optional)
            </span>
          </span>
          <span class="file-name"></span>
        </label>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :steps, class: "label" %>
    <div class="control">
      <%= form.text_area :steps, placeholder: "Start typing the steps...", class: "input", rows: "15"  %>
    </div>
  </div>

  <div class="field is-grouped is-grouped-right">
    <div class="control">
      <%= form.submit "Submit", class: "button is-primary" %>
    </div>
    <div class="control">
      <%= link_to "Cancel", :back, class: "button is-primary is-light" %>
    </div>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="column is-4">
  <div class="card">
    <div class="card-image">
      <figure class="image is-2by1">
        <%= image_tag recipe.picture if recipe.picture.attached? %>
      </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <div class="block">
            <h2 class="title has-text-primary">
              <%= recipe.name %>
            </h2>
            <h5 class="has-text-primary subtitle" style="float: inline-end;">
              By: <%= recipe.user.name %>
            </h5>
            <h4 class="subtitle has-text-grey-dark">
              <%= recipe.recipe_category.name %>
            </h4>
          </div>
          <div class="block">
            <p class="subtitle is-6 has-text-dark">
              <%= recipe.description %>
            </p>
          </div>
          <div class="block">
            <h4 class="subtitle has-text-primary">Ingredients</h4>
            <div class="tags">
              <% parsed_ingredients(recipe).each do |ingredient| %>
                <%= tag.span "", class: "tag is-success" do %>
                  <%= ingredient["name"].titleize %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

    </div>
    <footer class="card-footer">
      <%= link_to "Details", recipe, class: "button card-footer-item is-primary" %>
      <%= link_to "Edit", edit_recipe_path(recipe), class: "button card-footer-item  is-primary is-light" if policy(recipe).update? %>
      <%= button_to "Destroy", recipe, method: :delete, class: "button card-footer-item is-dark has-text-danger" if policy(recipe).destroy? %>
    </footer>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="column">
  <h3 class="title has-text-white-ter has-text-right">Edit recipe
  </h3>
  <div class="columns">
    <div class="column box">
      <%= hidden_field_tag :current_recipe_path, "edit" %>
      <%= render "form", recipe: @recipe %>
    </div>
  </div>
</div>

<script type="text/javascript">
  const currentAppliances = '<%= @recipe.appliances.join(",") %>'.split(",");
  const currentIngredients = '<%= @recipe.ingredients.to_json.html_safe %>';
</script>

app/views/recipes/index.html.erb
<div class="column">
  <h3 class="title has-text-white-ter has-text-right">
    <%= "#{@recipe_scope == "user" ? "My recipes" : "Recipes"}" %>
  </h3>
  <hr class="login-hr">
  <p class="subtitle has-text-white-ter has-text-right">
    <%= "#{@recipe_scope == "user" ? "I have" : "The community has"} already created #{@recipes.length} #{@recipes.length == 1 ? "recipe" : "recipe".pluralize}!" %>
  </p>
  <div class="block">
    <%= link_to "Create new recipe", new_recipe_path, class: "button is-success" %>
  </div>

  <div class="columns is-multiline">    
    <% @recipes.each do |recipe| %>
      <%= render recipe %>
    <% end %>
  </div>

</div>

app/views/recipes/new.html.erb
<div class="column">
  <h3 class="title has-text-white-ter has-text-right">New recipe
  </h3>
  <div class="columns">
    <div class="column box">
      <%= hidden_field_tag :current_recipe_path, "new" %>
      <%= render "form", recipe: @recipe %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="card">
  <div class="card-image">
    <figure class="image is-3by1">
      <%= image_tag @recipe.picture if @recipe.picture.attached? %>
    </figure>
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <div class="level">
          <div class="level-left is-8">
            <div class="level-item">
              <h2 class="title has-text-primary">
                <%= @recipe.name %>
              </h2>
            </div>
            <div class="level-item">
              <p class="subtitle has-text-grey-dark">
                <%= @recipe.recipe_category.name %>
              </p>
            </div>
          </div>
          <div class="level-right is-4 has-text-right">
            <div class="level-item">
              <h3 class="has-text-primary">
                By: <%= @recipe.user.name %>
              </h3>
            </div>
          </div>
        </div>
        <div class="level">
          <div class="level-left is-8">
            <div class="level-item">
              <p class="subtitle is-6 has-text-dark">
                <%= @recipe.description %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="content">
      <div class="columns">
        <div class="column is-8">
          <h4 class="title has-text-primary">Ingredients</h4>
          <ul>
            <% @ingredients_json.each do |ingredient| %>
              <%= tag.li "#{ingredient["name"].titleize}: #{ingredient["quantity"]} #{ingredient["quantity"].to_i > 1 ? ingredient["measure"].pluralize : ingredient["measure"]}" %>
            <% end %>
          </ul>
        </div>
        <div class="column is-4">
          <h4 class="title has-text-primary">Appliances</h4>
          <ul>
            <% @recipe.appliances.each do |appliance| %>
              <%= tag.li appliance.titleize %>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="column">
        <h4 class="title has-text-primary">Steps</h4>
        <%= tag.ol do %>
          <% @recipe.steps.each do |step| %>
            <%= tag.li do %>
              <%= tag.label "", class: "checkbox" do %>
                <input type="checkbox">
                <%= step.capitalize %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="column">
        <h4 class="title has-text-primary">Steps video</h4>
        <% if @recipe.steps_video.attached? %>
          <%= tag.figure class: "is-3by1" do %>
            <%= video_tag rails_blob_path(@recipe.steps_video), controls: true %>
          <% end %>
        <% else %>
          <%= tag.p "This video is unavailable" %>
        <% end %>
      </div>
    </div>
  </div>
  <footer class="card-footer">
    <%= link_to "Back", recipes_path, class: "button card-footer-item is-primary" %>
    <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "button card-footer-item  is-primary is-light" if policy(@recipe).update? %>
    <%= button_to "Destroy this recipe", @recipe, method: :delete, class: "button card-footer-item is-dark has-text-danger" if policy(@recipe).destroy? %>
  </footer>
</div>