config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :recipes
  devise_for :users
  root "home#index"
  resources :recipes

  scope "/admin" do
    resources :ingredients, except: %i[show]
    resources :ingredient_categories, except: %i[show]
    resources :recipe_categories, except: %i[show]
    resources :appliances, except: %i[show]
    resources :users, except: %i[show new create]
    resources :inventories
  end
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  validates :name, uniqueness: true

  MEASURES = %w[cup oz ml floz
                g kg piece leaf
                pinch lb tsp tbsp].freeze

  CATEGORIES = IngredientCategory.pluck("name").sort
end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true

class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[edit update destroy]
  before_action :set_authorization

  # GET /ingredients
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  def show; end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit; end

  # POST /ingredients
  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      redirect_to ingredients_url, notice: "Ingredient was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /ingredients/1
  def update
    if @ingredient.update(ingredient_params)
      redirect_to ingredients_url, notice: "Ingredient was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /ingredients/1
  def destroy
    @ingredient.destroy

    redirect_to ingredients_url, notice: "Ingredient was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def set_authorization
    authorize Ingredient
  end

  # Only allow a list of trusted parameters through.
  def ingredient_params
    params.require(:ingredient).permit(:name, :category)
  end
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient) do |form| %>
  <% if ingredient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <label class="label">Name & category</label>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control">
          <%= form.text_field :name, autofocus: true, class: "input" %>
        </p>
      </div>
      <div class="field">
        <div class="control">
          <div class="select is-primary">
            <%= form.select :category, Ingredient::CATEGORIES, prompt: "Choose a category" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  

  <div class="actions has-text-right">
    <%= link_to "Back to ingredients", ingredients_path, class: "button is-link" %>
    <%= form.submit "Update", class: "button is-primary is-outlined" %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<div class="column">
  <h3 class="title has-text-white-ter has-text-right">Edit ingredient
  </h3>

  <div class="columns">
    <div class="column box">
      <%= render "form", ingredient: @ingredient %>
    </div>
  </div>

</div>

app/views/ingredients/index.html.erb
<div class="column">
  <h3 class="title has-text-white-ter has-text-right">
    Ingredients
  </h3>
  <hr class="login-hr">
  <p class="subtitle has-text-white-ter has-text-right">
    <!-- TODO: pluralize item amount text -->
    <%= "We already have #{@ingredients.length} ingredients!" %>
  </p>
  <div class="block">
    <%= link_to "New ingredient", new_ingredient_path, class: "button is-success" %>
  </div>

  <div class="columns">
    <div class="column box">
      <table class="table is-striped is-hoverable has-text-centered is-fullwidth">
        <thead>
          <tr>
            <th>Name</th>
            <th>Category</th>
            <th>Updated at</th>
            <th>Created at</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          <% @ingredients.each do |ingredient| %>
            <tr>
              <td class="has-text-primary">
                <%= link_to ingredient.name, edit_ingredient_path(ingredient) %>
              </td>
              <%= tag.td ingredient.category %>
              <%= tag.td ingredient.updated_at %>
              <%= tag.td ingredient.created_at %>
              <td>
                <%= button_to "Destroy this ingredient", ingredient, method: :delete, class: "delete is-danger", data: { confirm: "Are you REALLY sure?" } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>

app/views/ingredients/new.html.erb
<div class="column">
  <h3 class="title has-text-white-ter has-text-right">New ingredient
  </h3>

  <div class="columns">
    <div class="column box">
      <%= render "form", ingredient: @ingredient %>
    </div>
  </div>

</div>