config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :recipes
  devise_for :users
  root "home#index"
  resources :recipes

  scope "/admin" do
    resources :ingredients, except: %i[show]
    resources :ingredient_categories, except: %i[show]
    resources :recipe_categories, except: %i[show]
    resources :appliances, except: %i[show]
    resources :users, except: %i[show new create]
    resources :inventories
  end
end

app/models/ingredient_category.rb
# frozen_string_literal: true

class IngredientCategory < ApplicationRecord
end

app/controllers/ingredient_categories_controller.rb
# frozen_string_literal: true

class IngredientCategoriesController < ApplicationController
  before_action :set_ingredient_category, only: %i[edit update destroy]
  before_action :set_authorization

  # GET /ingredient_categories or /ingredient_categories.json
  def index
    @ingredient_categories = IngredientCategory.all
  end

  # GET /ingredient_categories/new
  def new
    @ingredient_category = IngredientCategory.new
  end

  # GET /ingredient_categories/1/edit
  def edit; end

  # POST /ingredient_categories
  def create
    @ingredient_category = IngredientCategory.new(ingredient_category_params)

    if @ingredient_category.save
      redirect_to ingredient_categories_url, notice: "Ingredient category was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /ingredient_categories/1 or /ingredient_categories/1.json
  def update
    if @ingredient_category.update(ingredient_category_params)
      redirect_to ingredient_categories_url, notice: "Ingredient category was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /ingredient_categories/1 or /ingredient_categories/1.json
  def destroy
    @ingredient_category.destroy

    redirect_to ingredient_categories_url, notice: "Ingredient category was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ingredient_category
    @ingredient_category = IngredientCategory.find(params[:id])
  end

  def set_authorization
    authorize IngredientCategory
  end

  # Only allow a list of trusted parameters through.
  def ingredient_category_params
    params.require(:ingredient_category).permit(:name)
  end
end

app/views/ingredient_categories/_form.html.erb
<%= form_with(model: ingredient_category) do |form| %>
  <% if ingredient_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ingredient_category.errors.count, "error") %> prohibited this ingredient_category from being saved:</h2>

      <ul>
        <% ingredient_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <label class="label">Name</label>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control">
          <%= form.text_field :name, autofocus: true, class: "input" %>
        </p>
      </div>
    </div>
  </div>

  <div class="actions has-text-right">
    <%= link_to "Back to ingredient categories", ingredient_categories_path, class: "button is-link" %>
    <%= form.submit "Update", class: "button is-primary is-outlined" %>
  </div>
<% end %>

app/views/ingredient_categories/edit.html.erb
<div class="column">
  <h3 class="title has-text-white-ter has-text-right">Edit ingredient category
  </h3>

  <div class="columns">
    <div class="column box">
      <%= render "form", ingredient_category: @ingredient_category %>
    </div>
  </div>

</div>

app/views/ingredient_categories/index.html.erb
<div class="column">
  <h3 class="title has-text-white-ter has-text-right">
    Ingredient categories
  </h3>
  <hr class="login-hr">
  <p class="subtitle has-text-white-ter has-text-right">
    <!-- TODO: pluralize item amount text -->
    <%= "We already have #{@ingredient_categories.length} ingredient categories!" %>
  </p>
  <div class="block">
    <%= link_to "New ingredient category", new_ingredient_category_path, class: "button is-success" %>
  </div>

  <div class="columns">
    <div class="column box">
      <table class="table is-striped is-hoverable has-text-centered is-fullwidth">
        <thead>
          <tr>
            <th>Name</th>
            <th>Updated at</th>
            <th>Created at</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          <% @ingredient_categories.each do |ingredient_category| %>
            <tr>
              <td class="has-text-primary">
                <%= link_to ingredient_category.name, edit_ingredient_category_path(ingredient_category) %>
              </td>
              <%= tag.td ingredient_category.updated_at %>
              <%= tag.td ingredient_category.created_at %>
              <td>
                <%= button_to "Destroy this ingredient category", ingredient_category, method: :delete, class: "delete is-danger", data: { confirm: "Are you REALLY sure?" } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/ingredient_categories/new.html.erb
<div class="column">
  <h3 class="title has-text-white-ter has-text-right">New ingredient category
  </h3>

  <div class="columns">
    <div class="column box">
      <%= render "form", ingredient_category: @ingredient_category %>
    </div>
  </div>

</div>