config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :recipes
  devise_for :users
  root "home#index"
  resources :recipes

  scope "/admin" do
    resources :ingredients, except: %i[show]
    resources :ingredient_categories, except: %i[show]
    resources :recipe_categories, except: %i[show]
    resources :appliances, except: %i[show]
    resources :users, except: %i[show new create]
    resources :inventories
  end
end

app/views/layouts/_navbar.html.erb
<div class="hero-head">
  <nav class="navbar navbar">
    <div class="navbar-brand">
      <%= link_to("/", class: "navbar-item") do %>
        <span class="icon title">
          <i class="fas fa-pastafarianism"></i>
        </span>
        <span class="title">mogumogu</span>
      <% end %>
      <span role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarMenu">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </span>
    </div>
    <div id="navbarMenu" class="navbar-menu">
      <% if user_signed_in? %>
        <div class="navbar-end">
          <span class="navbar-item">
            <%= render "layouts/searchbar" %>
          </span>
        </div>
        <div class="navbar-end">
          <span class="navbar-item">
            <%= link_to(new_recipe_path) do %>
              <span class="icon">
                <i class="fas fa-plus-circle"></i>
              </span>
              New recipe
            <% end %>
          </span>

          <span class="navbar-item">
            <%= link_to(inventories_path) do %>
              <span class="icon">
                <i class="fas fa-cloud-meatball"></i>
              </span>
              My inventory
            <% end %>
          </span>

          <span class="navbar-item">
            <%= link_to(edit_user_registration_path) do %>
              <span>Hi, <i class="fas fa-user"></i> <%= current_user.name %>
              </span>
            <% end %>
          </span>

          <% if current_user.admin? %>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                <span class="icon" title="Admin tools">
                  <i class="fas fa-tools"></i>
                </span>
              </a>

              <div class="navbar-dropdown has-text-black">
                <%= link_to "Users", users_path, class: "navbar-item" %>
                <hr class="navbar-divider">
                <div class="navbar-item has-text-primary has-text-weight-semibold">
                  Recipes & stuff
                </div>
                <%= link_to "Ingredients", ingredients_path, class: "navbar-item" %>
                <%= link_to "Ingredient categories", ingredient_categories_path, class: "navbar-item" %>
                <%= link_to "Appliances", appliances_path, class: "navbar-item" %>
                <%= link_to "Recipe categories", recipe_categories_path, class: "navbar-item" %>
                <%= link_to "Recipes", "#", class: "navbar-item" %>
              </div>
            </div>
          <% end %>

          <span class="navbar-item">
            <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: 'button is-dark' %>
          </span>
        </div>
      <% else %>
        <div class="navbar-end">

          <span class="navbar-item">
            <%= link_to "Sign Up", new_user_registration_path, class:  "button is-dark" %>
          </span>

          <span class="navbar-item">
            <%= link_to(new_user_session_path, class: "button is-primary is-inverted is-outlined") do %>
              <span class="icon">
                <i class="fas fa-sign-in-alt"></i>
              </span>
              <span>Sign In
              </span>
            <% end %>
          </span>
        </div>
      <% end %>
    </div>
  </nav>
</div>

app/views/layouts/_searchbar.html.erb
<%= form_tag "/recipes", method: "GET" do %>
  <%= hidden_field_tag :is_searching, "searching" %>
  <div class="field has-addons has-addons-centered">
    <div class="control">
      <%= text_field_tag :search_by_ingredient, params[:search_by_ingredient], class: "input is-medium is-rounded is-dark", placeholder: "Search by ingredient" %>
    </div>
    <div class="control">
      <%= submit_tag "Search", class: "button is-medium is-rounded is-dark" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoguMogu</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://kit.fontawesome.com/7960f1a031.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <section class="hero is-primary is-fullheight">
      <%= render "layouts/navbar" %>
      <div class="hero-body">    
        <div class="container">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
        </div>
      </div>
    </section>
  </body>
</html>